Add check for empty comparison ref
Under some unexpected circumstances, the information used to determine the ref for the base of the comparison might be
missing, which would result in an empty definition for the ref. Since the `actions/checkout` action defaults to checking
out the tip of the default branch, this would not be reported and would result in spurious results. Better will be to
cause the relevant workflow step to fail with a helpful error message.

diff --git a/.github/workflows/compare-performance.yml b/.github/workflows/compare-performance.yml
--- a/.github/workflows/compare-performance.yml
+++ b/.github/workflows/compare-performance.yml
@@ -43,11 +43,11 @@ jobs:
         id: base-ref
         run: |
           if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
-            echo "::set-output name=ref::${{ github.event.inputs.comparison-ref }}"
+            COMPARISON_REF="${{ github.event.inputs.comparison-ref }}"
           elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
-            echo "::set-output name=ref::${{ github.base_ref }}"
+            COMPARISON_REF="${{ github.base_ref }}"
           elif [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
-            PREV_TAG="$( \
+            COMPARISON_REF="$( \
               git ls-remote \
               --quiet \
               --tags \
@@ -59,10 +59,16 @@ jobs:
                     tail -2 | \
                       head -1
             )"
-            echo "::set-output name=ref::$PREV_TAG"
           else
-            echo "::set-output name=ref::${{ github.event.before }}"
+            COMPARISON_REF="${{ github.event.before }}"
           fi
+
+          if [[ "$COMPARISON_REF" == "" ]]; then
+            echo "::error::Unable to determine comparison ref"
+            exit 1
+          fi
+
+          echo "::set-output name=ref::$COMPARISON_REF"
 
   run:
     name: Run at ${{ matrix.data.ref }} (${{ matrix.data.description }})
